#!/usr/bin/env bash
# Run the ProteoBench DIA-Astral *entrapment* (no-digestion) workflow for one
# (DIA-NN version x variable-mods) combination, via the `run-diann sushi` CLI
# adapter (readable keys, register_outputs=False — no B-Fabric, per Part 2 of
# TODO_entrapment_support.md; this is NOT the SUSHI GUI).
#
# Prerequisite: ./setup_integration_test.py  (downloads the FASTA + 6 Astral raws
# into input/, ~21 GB).
#
# The DIA-NN version and the mods arm are exposed as environment variables so you
# can re-run the same data for each version; each combo is written to its own
# clearly-named folder runs/diann-<version>-<mods>/ (work dir + outputs + the
# generated sushi_params.yml + Result_WU<version>_<mods>.zip).
#
# Usage:
#   ./run.sh                             # dry-run, VERSION=2.5.1 MODS=metox
#   ./run.sh run                         # execute
#   VERSION=2.5.0 MODS=nomods ./run.sh run
#   CORES=64 VERSION=2.3.2 ./run.sh run
#
#   VERSION  DIA-NN version -> pipeline_diann_version (container image tag).
#            Known-good: 2.3.2, 2.5.0, 2.5.1.
#   MODS     'metox'  -> --var-mods 1 --var-mod UniMod:35,15.994915,M (Met-ox)
#            'nomods' -> no variable modifications
#   CORES    thread count (default 32).
#
# run-diann auto-detects the container runtime (apptainer wins over docker); pass
# nothing special — the same command works on the docker dev box and the
# apptainer host.
set -euo pipefail
cd "$(dirname "$0")"
HERE="$(pwd)"

VERSION="${VERSION:-2.5.1}"
MODS="${MODS:-metox}"
CORES="${CORES:-32}"
MODE="${1:-dry}"

case "$MODS" in
  metox)  VARMODS="--var-mods 1 --var-mod UniMod:35,15.994915,M" ;;
  nomods) VARMODS="None" ;;
  *) echo "MODS must be 'metox' or 'nomods' (got: '$MODS')" >&2; exit 2 ;;
esac
case "$MODE" in dry|run) ;; *) echo "usage: $0 [dry|run]" >&2; exit 2 ;; esac

FASTA="$HERE/input/ProteoBenchFASTA_Entrapment_Human_with_contaminants_entrapment_pep.fasta"
RAWDIR="$HERE/input/raw"
COMBO="diann-${VERSION}-${MODS}"
OUT="$HERE/runs/$COMBO"
mkdir -p "$OUT"

# Generate the per-combo SUSHI-readable params. Only the DIA-NN version and the
# variable-mods arm change between combos; digestion is OFF (peptide-list FASTA).
cat > "$OUT/sushi_params.yml" <<YAML
# Generated by run.sh for combo ${COMBO} — do not edit (regenerated each run).
pipeline_diann_version: '${VERSION}'
pipeline_workflow_mode: two_step
pipeline_is_dda: 'false'
pipeline_raw_converter: native
input_fasta_use_custom: 'false'
input_fasta_databases: ${FASTA}
lib_digestion_cut: no digestion
lib_digestion_missed_cleavages: '0'
lib_peptide_min_length: '7'
lib_peptide_max_length: '30'
lib_precursor_charge_min: '2'
lib_precursor_charge_max: '4'
lib_precursor_mz_min: '380'
lib_precursor_mz_max: '980'
lib_fragment_mz_min: '200'
lib_fragment_mz_max: '1800'
lib_mods_variable: ${VARMODS}
lib_mods_no_peptidoforms: 'false'
lib_mods_unimod4: 'true'
lib_mods_met_excision: 'true'
search_mass_acc_ms1: AUTO
search_mass_acc_ms2: AUTO
search_scoring_qvalue: '0.01'
search_protein_pg_level: 1_protein_names
quant_scan_window: AUTO
quant_reanalyse: 'true'
quant_no_norm: 'false'
advanced_freestyle: None
advanced_verbose: '1'
YAML

ARGS=(sushi
  --params "$OUT/sushi_params.yml"
  --dataset "$HERE/input_dataset.tsv"
  --raw-dir "$RAWDIR"
  --fasta "$FASTA"
  --work-dir "$OUT" --output-dir "$OUT"
  --workunit-id "${VERSION}_${MODS}"
  --cores "$CORES")
[ "$MODE" = run ] || ARGS+=(-n)

echo "[$COMBO] run-diann ${ARGS[*]}"
run-diann "${ARGS[@]}"

# Dry-run materializes diann_runner_params.toml + dataset.csv in the combo dir;
# drop them so a later run doesn't read stale artifacts.
[ "$MODE" = run ] || rm -f "$OUT/diann_runner_params.toml" "$OUT/dataset.csv"
